[package]
name = "Benford"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse_mediawiki_dump = "0.1.0" #미디어위키 덤프 분석
regex = "1.5.4" #정규표현식